//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fooditem
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Fooditem()
        {
            this.MessAttandances = new HashSet<MessAttandance>();
        }
    
        public int FoodId { get; set; }
        public Nullable<int> MessId { get; set; }
        public int Price { get; set; }
        public string Dday { get; set; }
        public string FoodType { get; set; }
        public string FoodName { get; set; }
    
        public virtual MessMenue MessMenue { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessAttandance> MessAttandances { get; set; }
    }
}
