//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HostelSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomsDb
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomsDb()
        {
            this.AllotmentDbs = new HashSet<AllotmentDb>();
            this.MessAttandances = new HashSet<MessAttandance>();
        }
    
        public int Roomid { get; set; }
        public int RoomNo { get; set; }
        public string RoomCapacity { get; set; }
        public string Comments { get; set; }
        public string Details { get; set; }
        public Nullable<int> Hid { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AllotmentDb> AllotmentDbs { get; set; }
        public virtual HostelDb HostelDb { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MessAttandance> MessAttandances { get; set; }
    }
}
